export const staffs = [
  {
    employee_id: "111111",
    name: "John Doe",
    position: "Customer Support",
    email: "",
    phone: "",
    image: "/staff/1.jpg",
  },
  {
    employee_id: "222222",
    name: "Cindy Doe",
    position: "Customer Support",
    email: "",
    phone: "",
    image: "/staff/1.jpg",
  },
  {
    employee_id: "333333",
    name: "Hannah Doe",
    position: "Customer Support",
    email: "",
    phone: "",
    image: "/staff/1.jpg",
  },
  {
    employee_id: "444444",
    name: "Tom Doe",
    position: "Technical Support",
    email: "",
    phone: "",
    image: "/staff/1.jpg",
  },
  {
    employee_id: "555555",
    name: "Jane Doe",
    position: "Manager",
    email: "",
    phone: "",
    image: "/staff/1.jpg",
  },
];
