import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Nav_Bar from "./components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XR-TECH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <NextUIProvider  >
        <main className="dark text-foreground bg-background min-h-screen">
             <Nav_Bar />
             <div className="px-3">
            {children}
            </div>
            </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
